#%RAML 0.8
---
title: Amazon S3 REST API
version: 2006-03-01
baseUri: http://api.shilpa.com/{version}
mediaType: application/xml
traits: !include https://raw.github.com/sherenjal/amazon_example/master/content-headers.raml
/resource1:
